### ISSUE TITLE
Only 1st comment saved

### ISSUE THREAD

**Issue by samdroid-apps** [sugarlabs/reflect#2]
When adding a titled reflection (no JObject), if you add X (X > 1) comments then relaunch the activity, only the 1st comment is visible again.

**Comment by erilyth** [comment]
Could you tell me how I can reproduce this? Currently I am unable to get this error.

When I create comments, 
![screenshot from 2016-02-25 21 20 22](https://cloud.githubusercontent.com/assets/9864149/13325010/24bf99cc-dc06-11e5-8819-5f791f50e5cf.png)

Then I relaunch the activity and get this,
![screenshot from 2016-02-25 21 20 29](https://cloud.githubusercontent.com/assets/9864149/13325005/210c0446-dc06-11e5-97ea-9cad7fee800e.png)
and on showing the comments, all 4 are visible
![screenshot from 2016-02-25 21 20 32](https://cloud.githubusercontent.com/assets/9864149/13325000/1c5f485e-dc06-11e5-80f4-2a125f5d4cef.png)

**Comment by rhl-bthr** [comment]
I am also unable to reproduce the error. I am observing the same states as @erilyth.

**Comment by quozl** [comment]
Thanks @erilyth and @Pro-Panda for testing.  Plenty of commits since the issue was opened, so let's presume it was fixed.
